TOPLEVEL := ../../..
APP=cc
FALCON= ../../../flcn
all:
	$(FALCON)  connected_component.flcn
	mv connected_component.cpp connected_component.h connected_componentglobal.h $(TOPLEVEL)/CPU-Galois/generated/ccbin/
