TOPLEVEL := ../../../
APP=cc
FALCON= ../../../flcn
all:
	$(FALCON)  undirected_triangle_counting.flcn
	mv undirected_triangle_counting.cpp undirected_triangle_counting.h undirected_triangle_countingglobal.h $(TOPLEVEL)CPU/generated/tcbin/
